version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./lib/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_USERNAME=sdcatalog
      - MONGO_PASSWORD=sdcatalog
      - MONGO_DATABASE=sdcatalog
      - MONGO_COLLECTION=assets
