import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import Head from 'next/head'
import Typography from '@mui/material/Typography'

import CatalogHeader from '../components/CatalogHeader'

export async function getStaticProps() {
  // nextjs doesn't support environment variables in URLs used in getStaticProps
  //const res = await fetch(`${process.env.MOCK_API_HOST}/posts`)
  const res = await fetch('http://localhost:3001/assets')
  const assets = await res.json()

  return { props: { assets } }
}

export default function Index({ assets }) {
  return (
    <Container maxWidth="lg">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ my: 4 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          Temporary asset list
        </Typography>
        <CatalogHeader />
        <main>
          {assets.map((asset, i) => (
            <div key={`asset-${i}`}>
              {asset.name}@{asset.version}
            </div>
          ))}
        </main>
      </Box>
    </Container>
  )
}
